
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: LangChain dependencies an so on
    init: yarn
  - name: Start Ollama and the LLM
    init: |
      docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
      docker exec -it ollama ollama run tinydolphin
  - name: Start playing
    init: |
      cd 01-chat
      echo "👋 hello, try this: node about-star-wars.js"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - aaron-bond.better-comments
    - PKief.material-icon-theme
    - golang.go
    - PKief.material-product-icons
