
image: gitpod/workspace-full:latest

tasks:
  - name: Ollama-js and LangChain-js dependencies
    init: yarn
  - name: Ollama and tinydolphin
    init: |
      docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
      docker exec ollama ollama run tinydolphin
      cd 01-chat
      echo "👋 hello, try this: node about-star-wars.js"

vscode:
  extensions:
    - aaron-bond.better-comments
    - PKief.material-icon-theme
    - golang.go
    - PKief.material-product-icons
