
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: LangChain dependencies an so on
    command: yarn
  - name: Start Ollama
    command: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
  - name: Start a model
    command: docker exec -it ollama ollama run orca-mini
    #command: docker exec -it ollama ollama run llama2

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - pomdtr.excalidraw-editor
    - aaron-bond.better-comments
    - PKief.material-icon-theme
    - golang.go
    - PKief.material-product-icons
